package com.ayudaencasa.request.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "request")
public class Request implements Serializable {

    @DynamoDBHashKey (attributeName = "wId")
    @DynamoDBAutoGeneratedKey
    private String wId;
    @DynamoDBAttribute
    private String uId;
    @DynamoDBAttribute
    private String wMail;
    @DynamoDBAttribute
    private String wName;
    @DynamoDBAttribute
    private String wPhoto;
    @DynamoDBAttribute
    private String wProfession;
    @DynamoDBAttribute
    private int wTel;

    public String getwId() {
        return wId;
    }

    public void setwId(String wId) {
        this.wId = wId;
    }

    public String getuId() {
        return uId;
    }

    public void setuId(String uId) {
        this.uId = uId;
    }

    public String getwMail() {
        return wMail;
    }

    public void setwMail(String wMail) {
        this.wMail = wMail;
    }

    public String getwName() {
        return wName;
    }

    public void setwName(String wName) {
        this.wName = wName;
    }

    public String getwPhoto() {
        return wPhoto;
    }

    public void setwPhoto(String wPhoto) {
        this.wPhoto = wPhoto;
    }

    public String getwProfession() {
        return wProfession;
    }

    public void setwProfession(String wProfession) {
        this.wProfession = wProfession;
    }

    public int getwTel() {
        return wTel;
    }

    public void setwTel(int wTel) {
        this.wTel = wTel;
    }
}
